spring:
  datasource:
    username: root
    password: ms123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.222.152:9001/vike?characterEncoding=UTF-8


  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect