spring:
  datasource:
    username: root
    password: ms123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.13.222.152:9001/vike?characterEncoding=UTF-8


  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:logs/dev.xml

system:
  wx:
    app_id: wxe4d7a76e1414928a
    app_secret: 09496ecd52c61b453f8f96183d862acf
  hp:
    app_id: app_id
    app_secret: app_secret